import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

from xgboost import XGBClassifier

from config import (
    MODEL_TRAIN_FEATURES_PATH,
    RECOMMENDED_FEATURES_JSON,
    MODEL_PATH,
    FINAL_MODEL_METRICS_PATH,
    FINAL_MODEL_FEATURES_PATH,
)


# ============================================================
# SETTINGS
# ============================================================

RANDOM_STATE = 42

VALIDATION_SIZE = 0.20

EXPECTED_FEATURE_COUNT = 50

TARGET_COLUMN = "target"

ID_COLUMN = "sk_id_curr"

# Decision thresholds to evaluate.
#
# 0.50 is retained as the standard baseline.
# Lower thresholds increase recall and usually decrease
# precision.

THRESHOLDS = [
    0.20,
    0.25,
    0.30,
    0.35,
    0.40,
    0.45,
    0.50,
    0.55,
    0.60,
]


# ============================================================
# LOAD TRAINING DATA
# ============================================================

def load_training_data() -> pd.DataFrame:
    """
    Load the engineered training feature dataset.
    """

    if not MODEL_TRAIN_FEATURES_PATH.exists():

        raise FileNotFoundError(
            f"\nTraining feature dataset not found:\n"
            f"{MODEL_TRAIN_FEATURES_PATH}\n\n"
            f"Run feature_engineering.py first."
        )

    print(
        "\nLoading training feature dataset:"
    )

    print(
        MODEL_TRAIN_FEATURES_PATH
    )

    df = pd.read_parquet(
        MODEL_TRAIN_FEATURES_PATH
    )

    if df.empty:

        raise ValueError(
            "Training feature dataset is empty."
        )

    return df


# ============================================================
# LOAD SELECTED FEATURES
# ============================================================

def load_selected_features() -> list:
    """
    Load the recommended features generated by
    feature_selection.py.
    """

    if not RECOMMENDED_FEATURES_JSON.exists():

        raise FileNotFoundError(
            f"\nRecommended feature file not found:\n"
            f"{RECOMMENDED_FEATURES_JSON}\n\n"
            f"Run feature_selection.py first."
        )

    print(
        "\nLoading recommended features:"
    )

    print(
        RECOMMENDED_FEATURES_JSON
    )

    with open(
        RECOMMENDED_FEATURES_JSON,
        "r",
        encoding="utf-8",
    ) as file:

        report = json.load(
            file
        )

    if (
        "recommended_features"
        not in report
    ):

        raise ValueError(
            "recommended_features.json does not contain "
            "'recommended_features'."
        )

    features = (
        report[
            "recommended_features"
        ]
    )

    if not isinstance(
        features,
        list,
    ):

        raise ValueError(
            "'recommended_features' must be a list."
        )

    if len(features) != EXPECTED_FEATURE_COUNT:

        raise ValueError(
            f"Expected exactly "
            f"{EXPECTED_FEATURE_COUNT} selected features, "
            f"but found {len(features)}.\n\n"
            f"Run feature_selection.py again or update "
            f"EXPECTED_FEATURE_COUNT."
        )

    # --------------------------------------------------------
    # Duplicate check
    # --------------------------------------------------------

    if len(features) != len(
        set(features)
    ):

        raise ValueError(
            "Recommended feature list contains duplicates."
        )

    # --------------------------------------------------------
    # ID/target protection
    # --------------------------------------------------------

    forbidden_features = {
        ID_COLUMN,
        TARGET_COLUMN,
    }

    invalid_features = (
        forbidden_features
        .intersection(features)
    )

    if invalid_features:

        raise ValueError(
            "Recommended feature list contains forbidden "
            f"columns: {invalid_features}"
        )

    return features


# ============================================================
# VALIDATE DATASET
# ============================================================

def validate_dataset(
    df: pd.DataFrame,
    selected_features: list,
) -> None:
    """
    Validate the training dataset and selected feature list.
    """

    print(
        "\nValidating training dataset..."
    )

    # --------------------------------------------------------
    # Required columns
    # --------------------------------------------------------

    required_columns = {
        ID_COLUMN,
        TARGET_COLUMN,
    }

    missing_required = (
        required_columns
        .difference(df.columns)
    )

    if missing_required:

        raise ValueError(
            "Missing required columns: "
            f"{missing_required}"
        )

    # --------------------------------------------------------
    # Selected feature availability
    # --------------------------------------------------------

    missing_features = [
        feature
        for feature in selected_features
        if feature not in df.columns
    ]

    if missing_features:

        raise ValueError(
            "The following selected features are missing "
            "from the engineered dataset:\n"
            f"{missing_features}"
        )

    # --------------------------------------------------------
    # Target validation
    # --------------------------------------------------------

    if df[TARGET_COLUMN].isna().any():

        raise ValueError(
            "Target column contains missing values."
        )

    target_values = set(
        df[TARGET_COLUMN]
        .unique()
    )

    if not target_values.issubset(
        {0, 1}
    ):

        raise ValueError(
            "Target must contain only 0 and 1.\n"
            f"Found values: {target_values}"
        )

    # --------------------------------------------------------
    # Duplicate IDs
    # --------------------------------------------------------

    duplicate_ids = (
        df[ID_COLUMN]
        .duplicated()
        .sum()
    )

    print(
        f"Duplicate IDs: "
        f"{duplicate_ids:,}"
    )

    if duplicate_ids > 0:

        print(
            "WARNING: Duplicate applicant IDs detected."
        )

    # --------------------------------------------------------
    # Infinite values
    # --------------------------------------------------------

    numeric_columns = (
        df[
            selected_features
        ]
        .select_dtypes(
            include=["number"]
        )
        .columns
    )

    if len(numeric_columns) > 0:

        infinite_count = np.isinf(
            df[
                numeric_columns
            ]
            .to_numpy()
        ).sum()

    else:

        infinite_count = 0

    print(
        f"Infinite values in selected features: "
        f"{infinite_count:,}"
    )

    # --------------------------------------------------------
    # Target distribution
    # --------------------------------------------------------

    negative_count = int(
        (df[TARGET_COLUMN] == 0)
        .sum()
    )

    positive_count = int(
        (df[TARGET_COLUMN] == 1)
        .sum()
    )

    default_rate = (
        positive_count /
        len(df)
    )

    print(
        f"\nTarget 0: "
        f"{negative_count:,}"
    )

    print(
        f"Target 1: "
        f"{positive_count:,}"
    )

    print(
        f"Default rate: "
        f"{default_rate:.4%}"
    )

    print(
        "\nDataset validation completed."
    )


# ============================================================
# CLEAN FEATURES
# ============================================================

def clean_features(
    X: pd.DataFrame,
) -> pd.DataFrame:
    """
    Replace infinite values with NaN.

    The preprocessing pipeline subsequently handles NaN
    values using median/mode imputation.
    """

    X = X.copy()

    numeric_columns = (
        X.select_dtypes(
            include=["number"]
        )
        .columns
    )

    if len(numeric_columns) > 0:

        X[numeric_columns] = (
            X[numeric_columns]
            .replace(
                [np.inf, -np.inf],
                np.nan,
            )
        )

    return X


# ============================================================
# PREPROCESSOR
# ============================================================

def create_preprocessor(
    X_train: pd.DataFrame,
) -> ColumnTransformer:
    """
    Create preprocessing pipeline.

    Numeric
    -------
    Median imputation.

    Categorical
    -----------
    Most-frequent imputation.
    One-hot encoding.
    """

    numeric_features = (
        X_train
        .select_dtypes(
            include=["number"]
        )
        .columns
        .tolist()
    )

    categorical_features = (
        X_train
        .select_dtypes(
            include=[
                "object",
                "string",
                "category",
                "bool",
            ]
        )
        .columns
        .tolist()
    )

    transformers = []

    # --------------------------------------------------------
    # Numeric
    # --------------------------------------------------------

    if numeric_features:

        numeric_pipeline = Pipeline(
            steps=[
                (
                    "imputer",
                    SimpleImputer(
                        strategy="median"
                    ),
                )
            ]
        )

        transformers.append(
            (
                "numeric",
                numeric_pipeline,
                numeric_features,
            )
        )

    # --------------------------------------------------------
    # Categorical
    # --------------------------------------------------------

    if categorical_features:

        categorical_pipeline = Pipeline(
            steps=[
                (
                    "imputer",
                    SimpleImputer(
                        strategy="most_frequent"
                    ),
                ),
                (
                    "encoder",
                    OneHotEncoder(
                        handle_unknown="ignore",
                        sparse_output=True,
                    ),
                ),
            ]
        )

        transformers.append(
            (
                "categorical",
                categorical_pipeline,
                categorical_features,
            )
        )

    if not transformers:

        raise ValueError(
            "No numeric or categorical features found."
        )

    preprocessor = ColumnTransformer(
        transformers=transformers,
        remainder="drop",
    )

    return preprocessor


# ============================================================
# XGBOOST MODEL
# ============================================================

def create_xgboost_model(
    y_train: pd.Series,
) -> XGBClassifier:
    """
    Create XGBoost model.

    scale_pos_weight handles the Home Credit class imbalance.
    """

    negative_count = int(
        (y_train == 0).sum()
    )

    positive_count = int(
        (y_train == 1).sum()
    )

    if positive_count == 0:

        raise ValueError(
            "Training data contains no positive examples."
        )

    scale_pos_weight = (
        negative_count /
        positive_count
    )

    print(
        f"\nNegative samples: "
        f"{negative_count:,}"
    )

    print(
        f"Positive samples: "
        f"{positive_count:,}"
    )

    print(
        f"Scale positive weight: "
        f"{scale_pos_weight:.4f}"
    )

    model = XGBClassifier(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.80,
        colsample_bytree=0.80,
        min_child_weight=5,
        reg_alpha=0.10,
        reg_lambda=1.0,
        objective="binary:logistic",
        eval_metric="auc",
        scale_pos_weight=scale_pos_weight,
        random_state=RANDOM_STATE,
        n_jobs=-1,
        tree_method="hist",
    )

    return model


# ============================================================
# EVALUATE BASE MODEL
# ============================================================

def evaluate_model(
    model_pipeline: Pipeline,
    X_valid: pd.DataFrame,
    y_valid: pd.Series,
) -> tuple:
    """
    Evaluate model using probability predictions.

    Returns
    -------
    metrics
    probabilities
    """

    probabilities = (
        model_pipeline
        .predict_proba(
            X_valid
        )[:, 1]
    )

    predictions = (
        probabilities >= 0.50
    ).astype(int)

    metrics = {
        "roc_auc": float(
            roc_auc_score(
                y_valid,
                probabilities,
            )
        ),

        "pr_auc": float(
            average_precision_score(
                y_valid,
                probabilities,
            )
        ),

        "precision": float(
            precision_score(
                y_valid,
                predictions,
                zero_division=0,
            )
        ),

        "recall": float(
            recall_score(
                y_valid,
                predictions,
                zero_division=0,
            )
        ),

        "f1": float(
            f1_score(
                y_valid,
                predictions,
                zero_division=0,
            )
        ),

        "threshold": 0.50,

        "confusion_matrix":
            confusion_matrix(
                y_valid,
                predictions,
            ).tolist(),
    }

    return (
        metrics,
        probabilities,
    )


# ============================================================
# THRESHOLD ANALYSIS
# ============================================================

def evaluate_thresholds(
    y_valid: pd.Series,
    probabilities: np.ndarray,
) -> list:
    """
    Evaluate model performance across multiple probability
    thresholds.

    This is important for credit-risk decisioning because
    0.50 is not necessarily the optimal business threshold.
    """

    results = []

    for threshold in THRESHOLDS:

        predictions = (
            probabilities >= threshold
        ).astype(int)

        precision = precision_score(
            y_valid,
            predictions,
            zero_division=0,
        )

        recall = recall_score(
            y_valid,
            predictions,
            zero_division=0,
        )

        f1 = f1_score(
            y_valid,
            predictions,
            zero_division=0,
        )

        results.append(
            {
                "threshold":
                    float(threshold),

                "precision":
                    float(precision),

                "recall":
                    float(recall),

                "f1":
                    float(f1),

                "positive_prediction_rate":
                    float(
                        predictions.mean()
                    ),
            }
        )

    return results


# ============================================================
# SELECT BEST THRESHOLD
# ============================================================

def select_best_threshold(
    threshold_results: list,
) -> dict:
    """
    Select threshold using F1 as a baseline optimization
    criterion.

    This is NOT a final banking policy threshold.

    In a real lending environment, threshold selection should
    incorporate expected loss, approval rate, default cost,
    manual-review capacity and business policy.
    """

    if not threshold_results:

        raise ValueError(
            "No threshold evaluation results."
        )

    best = max(
        threshold_results,
        key=lambda result: (
            result["f1"],
            result["recall"],
        ),
    )

    return best


# ============================================================
# SAVE JSON
# ============================================================

def save_json(
    path: Path,
    data: dict,
) -> None:
    """
    Save dictionary as formatted JSON.
    """

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with open(
        path,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            data,
            file,
            indent=4,
        )


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 75)

    print(
        "FINAL HOME CREDIT XGBOOST MODEL TRAINING"
    )

    print("=" * 75)

    # ========================================================
    # LOAD
    # ========================================================

    df = load_training_data()

    print(
        f"\nDataset shape: "
        f"{df.shape}"
    )

    # ========================================================
    # LOAD SELECTED FEATURES
    # ========================================================

    selected_features = (
        load_selected_features()
    )

    print(
        f"\nSelected feature count: "
        f"{len(selected_features)}"
    )

    # ========================================================
    # VALIDATE
    # ========================================================

    validate_dataset(
        df,
        selected_features,
    )

    # ========================================================
    # DISPLAY SELECTED FEATURES
    # ========================================================

    print(
        "\n" + "=" * 75
    )

    print(
        "SELECTED FEATURES"
    )

    print(
        "=" * 75
    )

    for index, feature in enumerate(
        selected_features,
        start=1,
    ):

        print(
            f"{index:02d}. {feature}"
        )

    # ========================================================
    # CREATE X / Y
    # ========================================================

    X = df[
        selected_features
    ].copy()

    y = df[
        TARGET_COLUMN
    ].copy()

    # ========================================================
    # CLEAN
    # ========================================================

    X = clean_features(
        X
    )

    # ========================================================
    # TRAIN / VALIDATION SPLIT
    # ========================================================

    print(
        "\n" + "=" * 75
    )

    print(
        "TRAIN / VALIDATION SPLIT"
    )

    print(
        "=" * 75
    )

    (
        X_train,
        X_valid,
        y_train,
        y_valid,
    ) = train_test_split(
        X,
        y,
        test_size=VALIDATION_SIZE,
        stratify=y,
        random_state=RANDOM_STATE,
    )

    print(
        f"Training rows: "
        f"{len(X_train):,}"
    )

    print(
        f"Validation rows: "
        f"{len(X_valid):,}"
    )

    print(
        f"Training default rate: "
        f"{y_train.mean():.4%}"
    )

    print(
        f"Validation default rate: "
        f"{y_valid.mean():.4%}"
    )

    # ========================================================
    # PREPROCESSOR
    # ========================================================

    print(
        "\n" + "=" * 75
    )

    print(
        "BUILDING PREPROCESSOR"
    )

    print(
        "=" * 75
    )

    preprocessor = create_preprocessor(
        X_train
    )

    # ========================================================
    # MODEL
    # ========================================================

    model = create_xgboost_model(
        y_train
    )

    # ========================================================
    # PIPELINE
    # ========================================================

    pipeline = Pipeline(
        steps=[
            (
                "preprocessor",
                preprocessor,
            ),
            (
                "model",
                model,
            ),
        ]
    )

    # ========================================================
    # TRAIN
    # ========================================================

    print(
        "\n" + "=" * 75
    )

    print(
        "TRAINING FINAL XGBOOST MODEL"
    )

    print(
        "=" * 75
    )

    pipeline.fit(
        X_train,
        y_train,
    )

    print(
        "\nModel training completed."
    )

    # ========================================================
    # EVALUATION
    # ========================================================

    print(
        "\n" + "=" * 75
    )

    print(
        "MODEL EVALUATION"
    )

    print(
        "=" * 75
    )

    (
        metrics,
        probabilities,
    ) = evaluate_model(
        pipeline,
        X_valid,
        y_valid,
    )

    print(
        f"\nROC-AUC  : "
        f"{metrics['roc_auc']:.6f}"
    )

    print(
        f"PR-AUC   : "
        f"{metrics['pr_auc']:.6f}"
    )

    print(
        f"Precision: "
        f"{metrics['precision']:.6f}"
    )

    print(
        f"Recall   : "
        f"{metrics['recall']:.6f}"
    )

    print(
        f"F1 Score : "
        f"{metrics['f1']:.6f}"
    )

    print(
        "\nConfusion Matrix:"
    )

    print(
        np.array(
            metrics[
                "confusion_matrix"
            ]
        )
    )

    # ========================================================
    # THRESHOLD ANALYSIS
    # ========================================================

    print(
        "\n" + "=" * 75
    )

    print(
        "THRESHOLD ANALYSIS"
    )

    print(
        "=" * 75
    )

    threshold_results = (
        evaluate_thresholds(
            y_valid,
            probabilities,
        )
    )

    print(
        "\n"
        "Threshold | Precision | Recall | F1 | "
        "Predicted Default %"
    )

    print(
        "-" * 75
    )

    for result in threshold_results:

        print(
            f"{result['threshold']:9.2f} | "
            f"{result['precision']:9.4f} | "
            f"{result['recall']:6.4f} | "
            f"{result['f1']:6.4f} | "
            f"{result['positive_prediction_rate']:.2%}"
        )

    best_threshold = (
        select_best_threshold(
            threshold_results
        )
    )

    print(
        "\nBest baseline F1 threshold:"
    )

    print(
        f"Threshold: "
        f"{best_threshold['threshold']:.2f}"
    )

    print(
        f"Precision: "
        f"{best_threshold['precision']:.4f}"
    )

    print(
        f"Recall: "
        f"{best_threshold['recall']:.4f}"
    )

    print(
        f"F1: "
        f"{best_threshold['f1']:.4f}"
    )

    # ========================================================
    # FEATURE IMPORTANCE
    # ========================================================

    print(
        "\n" + "=" * 75
    )

    print(
        "FEATURE IMPORTANCE"
    )

    print(
        "=" * 75
    )

    trained_preprocessor = (
        pipeline.named_steps[
            "preprocessor"
        ]
    )

    trained_model = (
        pipeline.named_steps[
            "model"
        ]
    )

    transformed_feature_names = (
        trained_preprocessor
        .get_feature_names_out()
    )

    model_importances = (
        trained_model
        .feature_importances_
    )

    transformed_importance_df = (
        pd.DataFrame(
            {
                "feature":
                    transformed_feature_names,

                "importance":
                    model_importances,
            }
        )
        .sort_values(
            "importance",
            ascending=False,
        )
        .reset_index(
            drop=True
        )
    )

    print(
        "\nTop 20 transformed features:"
    )

    print(
        transformed_importance_df
        .head(20)
        .to_string(
            index=False
        )
    )

    # ========================================================
    # ORIGINAL FEATURE IMPORTANCE
    # ========================================================

    original_importance = []

    for feature in selected_features:

        total_importance = 0.0

        for (
            transformed_name,
            importance,
        ) in zip(
            transformed_feature_names,
            model_importances,
        ):

            cleaned_name = (
                transformed_name
            )

            if "__" in cleaned_name:

                cleaned_name = (
                    cleaned_name
                    .split(
                        "__",
                        1,
                    )[1]
                )

            if (
                cleaned_name == feature
                or cleaned_name.startswith(
                    feature + "_"
                )
            ):

                total_importance += float(
                    importance
                )

        original_importance.append(
            {
                "feature": feature,
                "importance":
                    total_importance,
            }
        )

    original_importance_df = (
        pd.DataFrame(
            original_importance
        )
        .sort_values(
            "importance",
            ascending=False,
        )
        .reset_index(
            drop=True
        )
    )

    print(
        "\nTop selected original features:"
    )

    print(
        original_importance_df
        .head(20)
        .to_string(
            index=False
        )
    )

    # ========================================================
    # FINAL METRICS
    # ========================================================

    final_metrics = {
        "model":
            "XGBoost",

        "dataset_rows":
            int(len(df)),

        "dataset_columns":
            int(df.shape[1]),

        "feature_count":
            int(len(selected_features)),

        "roc_auc":
            metrics["roc_auc"],

        "pr_auc":
            metrics["pr_auc"],

        "precision_at_0_50":
            metrics["precision"],

        "recall_at_0_50":
            metrics["recall"],

        "f1_at_0_50":
            metrics["f1"],

        "confusion_matrix_at_0_50":
            metrics[
                "confusion_matrix"
            ],

        "threshold_analysis":
            threshold_results,

        "best_baseline_f1_threshold":
            best_threshold,

        "random_state":
            RANDOM_STATE,

        "validation_size":
            VALIDATION_SIZE,

        "selected_features":
            selected_features,

        "feature_importance":
            original_importance_df
            .to_dict(
                orient="records"
            ),
    }

    # ========================================================
    # SAVE MODEL
    # ========================================================

    MODEL_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    print(
        "\n" + "=" * 75
    )

    print(
        "SAVING MODEL"
    )

    print(
        "=" * 75
    )

    joblib.dump(
        pipeline,
        MODEL_PATH,
    )

    print(
        f"\nModel saved to:"
    )

    print(
        MODEL_PATH
    )

    # ========================================================
    # SAVE METRICS
    # ========================================================

    save_json(
        FINAL_MODEL_METRICS_PATH,
        final_metrics,
    )

    print(
        "\nMetrics saved to:"
    )

    print(
        FINAL_MODEL_METRICS_PATH
    )

    # ========================================================
    # SAVE FEATURE LIST
    # ========================================================

    feature_report = {
        "feature_count":
            len(selected_features),

        "features":
            selected_features,

        "selection_source":
            str(
                RECOMMENDED_FEATURES_JSON
            ),

        "model":
            "XGBoost",

        "random_state":
            RANDOM_STATE,
    }

    save_json(
        FINAL_MODEL_FEATURES_PATH,
        feature_report,
    )

    print(
        "\nFeature report saved to:"
    )

    print(
        FINAL_MODEL_FEATURES_PATH
    )

    # ========================================================
    # RELOAD MODEL VERIFICATION
    # ========================================================

    print(
        "\n" + "=" * 75
    )

    print(
        "VERIFYING SAVED MODEL"
    )

    print(
        "=" * 75
    )

    loaded_pipeline = joblib.load(
        MODEL_PATH
    )

    if not isinstance(
        loaded_pipeline,
        Pipeline,
    ):

        raise ValueError(
            "Saved model is not a sklearn Pipeline."
        )

    if (
        "preprocessor"
        not in loaded_pipeline.named_steps
    ):

        raise ValueError(
            "Saved pipeline does not contain "
            "'preprocessor'."
        )

    if (
        "model"
        not in loaded_pipeline.named_steps
    ):

        raise ValueError(
            "Saved pipeline does not contain "
            "'model'."
        )

    # --------------------------------------------------------
    # Prediction verification
    # --------------------------------------------------------

    sample_size = min(
        10,
        len(X_valid),
    )

    sample_predictions = (
        loaded_pipeline
        .predict_proba(
            X_valid.iloc[
                :sample_size
            ]
        )[:, 1]
    )

    if not np.isfinite(
        sample_predictions
    ).all():

        raise ValueError(
            "Saved model produced invalid "
            "probability predictions."
        )

    print(
        "\nSaved model reload: SUCCESS"
    )

    print(
        "Preprocessor: FOUND"
    )

    print(
        "XGBoost model: FOUND"
    )

    print(
        "Prediction test: SUCCESS"
    )

    print(
        "\nSample predicted probabilities:"
    )

    print(
        sample_predictions
    )

    # ========================================================
    # FINAL STATUS
    # ========================================================

    print(
        "\n" + "=" * 75
    )

    print(
        "FINAL MODEL READY"
    )

    print(
        "=" * 75
    )

    print(
        "\nModel:"
    )

    print(
        MODEL_PATH
    )

    print(
        "\nFeatures:"
    )

    print(
        f"{len(selected_features)} selected features"
    )

    print(
        "\nROC-AUC:"
    )

    print(
        f"{metrics['roc_auc']:.6f}"
    )

    print(
        "\nPR-AUC:"
    )

    print(
        f"{metrics['pr_auc']:.6f}"
    )

    print(
        "\nBaseline threshold:"
    )

    print(
        "0.50"
    )

    print(
        "\nBest F1 threshold:"
    )

    print(
        f"{best_threshold['threshold']:.2f}"
    )

    print(
        "\nThe complete preprocessing + "
        "XGBoost pipeline is ready for FastAPI."
    )

    print(
        "\nNext stage:"
    )

    print(
        "API / prediction service integration."
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    main()
